import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string;
const supabaseKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

export const supabase = createClient(supabaseUrl, supabaseKey);

/*
 * ─── Esquema de tabla creado en Supabase ───
 *
 * Table: public.formulario_contactos_wasakabe
 *
 * id         bigint                 PK  (generated by default as identity)
 * created_at timestamptz                (default now())
 * name       text                    null
 * email      text                    null
 * subject    text                    null
 * messages   text                    null
 *
 * SQL de creación:
 *
 *   create table public.formulario_contactos_wasakabe (
 *     id bigint generated by default as identity not null,
 *     created_at timestamp with time zone not null default now(),
 *     name text null,
 *     email text null,
 *     subject text null,
 *     messages text null,
 *     constraint formulario_contactos_wasakabe_pkey primary key (id)
 *   ) tablespace pg_default;
 *
 * ─── Política de inserción anónima ───
 *
 * Ve a Authentication > Policies y agrega:
 *
 *   create policy "anon_insert" on public.formulario_contactos_wasakabe
 *     for insert to anon
 *     using (true)
 *     with check (true);
 */
